### ISSUE TITLE
Support both PulsePal v1.X and PulsePal v2.X USB interfaces

### ISSUE THREAD

**Issue by glopesdev** [bonsai-rx/pulsepal#3]

**Comment by RoboDoig** [comment]
Noticed while looking through the interface specs between 1.X and 2.X and comparing with Python implementation, seems that some places in the documentation have not updated the changes between versions with regards to data type of certain parameters. For example for setFixedVoltage, in the Python implementation the version change is that the voltage value is uint16 rather than uint8 - but in the documentation of the USB interface setFixedVoltage refers to a single byte for the voltage value in both 1.X and 2.X.

Assuming that the Python implementation is correct, was the documentation for 2.X USB interface not updated?
